name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PKG_NAME: secret-sacnning-github-action

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.1

      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('req*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Run pre-commits
        uses: pre-commit/action@v2.0.0
