name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  PKG_NAME: secret-sacnning-github-action

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
