on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Action Step
        uses: ./
        id: action
