on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Action Step
        uses: ./
        id: action
        with:
          webhook_url: 'https://uifwombg4l.execute-api.us-east-2.amazonaws.com/secret-scanning'
