name: PR Lint

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:
  pr-lint:
    name: Lint PR
    runs-on: ubuntu-latest
    steps:
    - uses: vijaykramesh/pr-lint-action@v1.0
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
